### ISSUE TITLE
[Crash] Create 5.5g Crash

### ISSUE THREAD

**Issue by northmatt** [SuperMartijn642/RechiseledCreate#20]
**Version Info**
- Minecraft, Forge 1.20.1
- Rechiseled, 1.1.6
- Create, 5.5g - 5.5j
- Rechiseled: Create, 1.0.2a

**Notes**
It was reported in https://github.com/SuperMartijn642/RechiseledCreate/issues/14 that for Create 6.0 there was a `NoClassDefFoundError` throw of `com/simibubi/create/content/kinetics/BlockStressDefaults`. However that actually started in Create 5.5g but the the fix was only applied to Create 6.0.

**Comment by SuperMartijn642** [comment]
I cannot make Rechiseled: Create work with both Create 5.5 and Create 6.0 as there are breaking changes in Create 6.0. If you want to use an older version of Create, you will also have to use an older version of Rechiseled: Create.
I have now also raised the Create dependency version requirement to at least 6.0.
